# 딥러닝 개괄
## 앞으로 공부할 주요 내용 코드로 정리

## 1. 환경 준비

In [2]:
# 텐서플로의 케라스 API에서 필요한 함수들을 불러옵니다.
# 데이터를 다루는데 필요한 라이브러리를 불러옵니다.
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense  
import numpy as np

2023-05-05 15:56:20.843891: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

## 2. 데이터 준비

In [3]:
# 준비된 수술 환자 데이터를 불러옵니다.
Data_set = np.loadtxt("./data/ThoraricSurgery3.csv", delimiter=",")
# 환자의 진찰 기록을 X로 지정합니다.
X = Data_set[:,0:16]                                                 
# 수술 후 사망/생존 여부를 y로 지정합니다.
y = Data_set[:,16]

## 3. 구조 결정

In [4]:
# 딥러닝 모델의 구조를 결정합니다.
model = Sequential()                                                  
model.add(Dense(30, input_dim=16, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

## 4. 모델 실행

In [6]:
# 딥러닝 모델을 실행합니다.
model.compile(loss = 'binary_crossentropy',
              optimizer = 'adam',
              metrics = ['accuracy'])

history = model.fit(X, y, epochs=5, batch_size=16)

Epoch 1/5
30/30 [==============================] - 0s 1ms/step - loss: 0.4196 - accuracy: 0.8511
Epoch 2/5
30/30 [==============================] - 0s 1ms/step - loss: 0.4093 - accuracy: 0.8511
Epoch 3/5
30/30 [==============================] - 0s 1ms/step - loss: 0.4126 - accuracy: 0.8532
Epoch 4/5
30/30 [==============================] - 0s 1ms/step - loss: 0.4185 - accuracy: 0.8532
Epoch 5/5
30/30 [==============================] - 0s 988us/step - loss: 0.4101 - accuracy: 0.8511

### 예제 데이터 구조

In [10]:
# 예제 데이터 구조 확인
import pandas as pd
pd.DataFrame(Data_set)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,1.0,2.88,2.16,1.0,0.0,0.0,0.0,1.0,1.0,3.0,0.0,0.0,0.0,1.0,0.0,60.0,0.0
1,2.0,3.40,1.88,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,51.0,0.0
2,2.0,2.76,2.08,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,59.0,0.0
3,2.0,3.68,3.04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,54.0,0.0
4,2.0,2.44,0.96,2.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,73.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
465,1.0,3.88,2.12,1.0,0.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,1.0,0.0,63.0,0.0
466,2.0,3.76,3.12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,61.0,0.0
467,2.0,3.04,2.08,1.0,0.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,52.0,0.0
468,2.0,1.96,1.68,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,79.0,0.0
469,2.0,4.72,3.56,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,51.0,0.0